# For more information, please refer to https://aka.ms/vscode-docker-python
FROM python:3.14-slim-trixie
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/


# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1


COPY . /app

WORKDIR /app

RUN uv sync --frozen --extra examples


EXPOSE 5000


CMD ["bash", "examples/auth0_demo/run_login_provider.sh"]
# Creates a non-root user with an explicit UID and adds permission to access the /src folder
# For more info, please refer to https://aka.ms/vscode-docker-python-configure-containers


# During debugging, this entry point will be overridden. For more information, please refer to https://aka.ms/vscode-docker-python-debug

